export class entry{
  id:number;
  val1:number;
  val2:number;
  val3:number;
  val4:number;
  val5:number;
  val6:number;
  val7:number;
  val8:number;
  val9:number;
  val10:number;
  val11:number;
  val12:number;
  val13:number;
  val14:number;
  val15:number;
  val16:number;
  val17:number;
  val18:number;
  val19:number;
  val20:number;
}
